version: 2.1

parameters:
  used:
    type: boolean
    default: true

executors:
# environment that jobs will run in
  builder:
    docker:
      - image: toodleloo/builder:latest
        # auth:
        #   username: $ECR_USER
        #   password: $ECR_PASSWORD

commands:
# re-usable code snippets jobs can call
  install:
    parameters:
      prod:
        type: boolean
        default: false
    steps:
      - when:
          condition: << parameters.prod >>
          steps:
            - run: yarn --prod
      - unless:
          condition: << parameters.prod >>
          steps:
            - run: yarn
  allow-develop-diffs:
  # allows git diffs with develop
    steps:
      - run: |
          COMMIT_ID=$(git rev-parse HEAD)
          git checkout develop
          git checkout $COMMIT_ID
  docker-login:
    steps:
      - run: docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $AWS_ECR_ACCOUNT_URL

jobs:
# chunks of code run on an executor, see https://circleci.com/docs/2.0/jobs-steps/#jobs-overview
  build:
    executor: builder
    steps:
      - checkout
      - install
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-test:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      - allow-develop-diffs
      - run: |
          scope=$(./build-scripts/get-packages-to-test.sh)
          scopeArgs=$(printf %s "${scope[@]/#/ --scope }")
          [ ! "$scopeArgs" = "" ] && yarn test:unit $scope
  build-push-image:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - docker-login
      - run: |
          image=$AWS_ECR_ACCOUNT_URL/app-sum:latest
          docker build -t $image apps/app-sum
          docker push $image

workflows:
# high level tasks performed automatically/scheduled
# every workflow will run on every commit unless filtered by branch
  version: 2
  test:
    unless: << pipeline.parameters.used >>
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - develop
      - unit-test:
          requires:
            - build
  build-push-images:
    when: << pipeline.parameters.used >>
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - build-push-image:
          requires:
            - build
          context: docker
